-- =====================================================================
-- Projet 4 — API de Gestion d'un Blog (Articles & Commentaires)
-- V1 : schéma initial
-- =====================================================================

CREATE TABLE articles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    -- Permalien dérivé du titre ; stable dans le temps, donc unique.
    slug             VARCHAR(250) NOT NULL,
    content          TEXT         NOT NULL,
    excerpt          VARCHAR(500),
    author           VARCHAR(100),
    category         VARCHAR(50),
    tags             TEXT,
    status           VARCHAR(20)  NOT NULL,
    view_count       INTEGER,
    publication_date TIMESTAMP(6),
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    CONSTRAINT uk_articles_slug UNIQUE (slug),
    CONSTRAINT ck_articles_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE TABLE comments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content        TEXT         NOT NULL,
    author_name    VARCHAR(100) NOT NULL,
    author_email   VARCHAR(100) NOT NULL,
    author_website VARCHAR(100),
    -- Un commentaire est créé en PENDING et n'est public qu'une fois APPROVED.
    status         VARCHAR(20)  NOT NULL,
    article_id     BIGINT       NOT NULL,
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),
    CONSTRAINT fk_comments_article FOREIGN KEY (article_id) REFERENCES articles (id),
    CONSTRAINT ck_comments_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- Les commentaires sont toujours lus par article, et filtrés par statut.
CREATE INDEX idx_comment_article_id ON comments (article_id);
CREATE INDEX idx_comments_article_status ON comments (article_id, status);

-- Le listing paginé trie par date de création décroissante.
CREATE INDEX idx_articles_created_at ON articles (created_at DESC);
